language: node_js
os: linux
dist: xenial
node_js:
  - 14.16.1
jobs:
  include:
    - stage: release
      node_js: 14.16.1
      script: 
        - npm run test:ci
        - npm run build
      deploy:
        - provider: script
          skip_cleanup: true
          script:
            - npx semantic-release
          on:
            all_branches: true
            condition: "$TRAVIS_BRANCH =~ ^(main|beta|alpha)$"
        - provider: pages
          skip_cleanup: true
          github-token: $GH_TOKEN
          target_branch: gh-pages
          local_dir: dist
          on:
            all_branches: true
            condition: "$TRAVIS_BRANCH =~ ^(main)$"
