name: Release
on:
  push:
    branches: [ main, beta ]

permissions:
  contents: read
  pull-requests: write
  issues: write
  repository-projects: write

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.6.1"
      - name: Install dependencies
        run: yarn install
      - name: build
        run: yarn build

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Semantic Release
        id: semantic
        run: npx semantic-release

  # Deploy job
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.6.1"
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/main'
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          folder: docs
          branch: gh-pages
